from __future__ import annotations

import os


DISCOVERY_MIN_CONFIDENCE = float(
    os.getenv("DOCENT_DISCOVERY_MIN_CONFIDENCE", "0.58")
)
DISCOVERY_RETRIEVAL_LIMIT = int(
    os.getenv("DOCENT_DISCOVERY_RETRIEVAL_LIMIT", "12")
)
DISCOVERY_CANDIDATE_LIMIT = int(
    os.getenv("DOCENT_DISCOVERY_CANDIDATE_LIMIT", "5")
)
DISCOVERY_EVIDENCE_PER_ARTWORK = int(
    os.getenv("DOCENT_DISCOVERY_EVIDENCE_PER_ARTWORK", "2")
)
DISCOVERY_PROXIMITY_SCORE_BAND = float(
    os.getenv("DOCENT_DISCOVERY_PROXIMITY_SCORE_BAND", "0.03")
)
